name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libxrandr-dev libx11-dev pkgconf
    
    - name: autoreconf
      run: autoreconf -is
      
    - name: configure --prefix=/usr
      run: ./configure
    
    - name: make
      run: make
    
    - name: Create deb
      run: |
        make install DESTDIR=build
        cp -r DEBIAN build
        dpkg-deb --build build spice-autorandr.deb
    
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: spice-autorandr
        path: spice-autorandr
    
    - name: Upload deb
      uses: actions/upload-artifact@v3
      with:
        name: spice-autorandr.deb
        path: spice-autorandr.deb
    
